export const ActionTypes = {
  // CONTROLLERS ------------------------

  //BURGER OPEN
  BURGER_MENU_OPEN : 'BURGER_MENU_OPEN',
  //BURGER CLOSE
  BURGER_MENU_CLOSE : 'BURGER_MENU_CLOSE',

  //SUCCESS MODAL OPEN
  SUCCESS_MODAL_OPEN : 'SUCCESS_MODAL_OPEN',
  //SUCCESS MODAL CLOSE
  SUCCESS_MODAL_CLOSE : 'SUCCESS_MODAL_CLOSE',

  //CURRENT PAGE
  HANDLE_CURRENT_PAGE : 'HANDLE_CURRENT_PAGE',
  //TOTAL PAGE
  HANDLE_TOTAL_PAGE : 'HANDLE_TOTAL_PAGE',



  // USERS ------------------------------

  //USERS GET
  USERS_GET_REQUEST: 'USERS_GET_REQUEST',
  USERS_GET_SUCCESS: 'USERS_GET_SUCCESS',
  USERS_GET_ERROR: 'USERS_GET_ERROR',

  //USER CREATE
  USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
  USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
  USER_CREATE_ERROR: 'USER_CREATE_ERROR',

  //POSITION GET
  POSITION_GET_REQUEST: 'POSITION_GET_REQUEST',
  POSITION_GET_SUCCESS: 'POSITION_GET_SUCCESS',
  POSITION_GET_ERROR: 'POSITION_GET_ERROR',

  //TOKEN GET
  TOKEN_GET_REQUEST: 'TOKEN_GET_REQUEST',
  TOKEN_GET_SUCCESS: 'TOKEN_GET_SUCCESS',
  TOKEN_GET_ERROR: 'TOKEN_GET_ERROR',

};